server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Kristina2024!
    url: jdbc:mysql://localhost:3306/polis-hospital
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
